name: macOS CI
on:
  push:
    paths:
      - '.github/*'
      - '3/*'
  pull_request:
    paths:
      - '.github/*'
      - '3/*'
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    env:
      CXXFLAGS: -Wno-error=deprecated-declarations
      INSPIRCD_DEBUG: 3
      INSPIRCD_VERBOSE: 1
    steps:
      - name: Checkout InspIRCd@insp3
        uses: actions/checkout@v4
        with:
          repository: 'inspircd/inspircd'
          ref: 'insp3'
          path: 'inspircd'
      - name: Checkout self
        uses: actions/checkout@v4
        with:
          path: 'contrib'
      - name: (Pull Request) Set the build target to only the changed modules
        if: github.event_name == 'pull_request'
        run: |
          cd contrib
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          echo INSPIRCD_TARGET=$( \
          git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | \
          for f in `cat`; do if [[ "$f" = "3/"*".cpp" ]]; \
          then echo "$(basename $f .cpp) "; fi; done) >> $GITHUB_ENV
      - name: (Push/PR Fallback) Set the build target to all of the modules
        if: github.event_name == 'push' || env.INSPIRCD_TARGET == ''
        run: echo INSPIRCD_TARGET=$(for f in contrib/3/*; do echo "$(basename $f .cpp) "; done) >> $GITHUB_ENV
      - name: Symlink the modules
        run: |
          cd inspircd/src/modules
          ln -s ../../../contrib/3/* .
      - name: Check for additional dependencies
        run: |
          cd inspircd
          echo PACKAGES=$( \
          for f in ../contrib/3/*; do if [[ "$INSPIRCD_TARGET" = *"$(basename $f .cpp)"* ]]; \
          then ./tools/directive $f PackageInfo; fi; done) >> $GITHUB_ENV
      - name: Install additional dependencies
        if: env.PACKAGES != ''
        run: |-
          brew update || true
          for PACKAGE in ${{ env.PACKAGES }}
          do
            brew install $PACKAGE || brew upgrade $PACKAGE
            BREW_PREFIX=$(brew --prefix $PACKAGE)
            if [ -d "$BREW_PREFIX/bin" ]
            then
              export PATH="$PATH:$BREW_PREFIX/bin"
            fi
            if [ -d "$BREW_PREFIX/lib/pkgconfig" ]
            then
              export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$BREW_PREFIX/lib/pkgconfig"
            fi
          done
          echo "CPPFLAGS=-I$(brew --prefix)/include" >> $GITHUB_ENV
          echo "LDFLAGS=-L$(brew --prefix)/lib" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
      - name: Build the modules
        run: |
          cd inspircd
          ./configure --development --disable-auto-extras
          make --jobs $(($(sysctl -n hw.activecpu) + 1))
